#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pydantic[email]>=2.0", "pyyaml>=6.0"]
# ///
"""tasks - an agent task manager over datafile.

One orchestrator creates tasks and dispatches them; each minion updates only
the task it owns. Concurrency is safe because the topology gives every key a
single writer at a time, not because of a lock. See README.md.
"""

from __future__ import annotations

import sys

VERSION = "0.1.0"

# AXI 10 fast path: answer a version probe before importing pydantic/yaml.
if __name__ == "__main__" and len(sys.argv) == 2 and sys.argv[1] in ("-v", "-V", "--version"):
    print(VERSION)
    raise SystemExit(0)

import contextlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
from datetime import UTC, datetime

PROG = "tasks.py"
DESCRIPTION = "Agent task manager where one orchestrator writes and minions report"
STORE = "tasks.jsonl"
STALE_DAYS = 14
VERIFY_TIMEOUT = 300
HOME_LIMIT = 5
CELL = 80
LIST_FIELDS = ("id", "status", "title")

# 7: session-integration identity. The ambient flag is what marks a hook as
# ours - unlike matching the script name, it survives an install made through a
# PATH alias the user later renames, so `setup` can still repair or remove it.
TOOL_NAME = "agent-tasks"
AMBIENT_FLAG = "--ambient"
HOOK_TIMEOUT = 10
OPENCODE_PREFIX = "axi managed opencode plugin:"
SKILL_NAME = TOOL_NAME
SKILL_PATH = os.path.join(".agents", "skills", SKILL_NAME, "SKILL.md")
SKILL_APPS = {"claude": (".claude", "skills"), "pi": (".agents", "skills")}
BIN_NAME = "tasks"                  # the name the README installs on PATH
PI_PACKAGE_DIR = "pi-" + TOOL_NAME
SKILL_TRIGGER = (
    "Queue, dispatch, and verify work for a fleet of agents from the command "
    "line. Use when an orchestrator needs to create tasks, hand one to a worker "
    "agent, record why something is blocked, reclaim an abandoned task, or find "
    "out what is ready to run next."
)
SLUG_BUDGET = 24       # ids appear in every suggestion line; keep them cheap
SLUG_STOP = {"a", "an", "the", "into", "for", "to", "of", "on", "in", "with",
             "and", "from", "at", "by", "as", "its", "it"}
TAIL_LINES = 20
STATUSES = ("todo", "doing", "done", "blocked")


# --------------------------------------------------------------- datafile load

def _find_datafile() -> str:
    """datafile.py is the storage engine. Locate it without vendoring a copy."""
    here = os.path.dirname(os.path.abspath(__file__))
    cands = [os.environ.get("TASKS_DATAFILE"),
             os.path.join(here, "datafile.py"),
             os.path.join(here, os.pardir, "datafile", "datafile.py")]
    found = shutil.which("datafile") or shutil.which("datafile.py")
    if found:
        cands.append(os.path.realpath(found))
    for c in cands:
        if c and os.path.isfile(c):
            return os.path.abspath(c)
    return ""


_DF = _find_datafile()
if not _DF:
    # Hand-rolled TOON: the module that owns emit() is the thing that is missing.
    print("error: datafile.py not found\ncode: DATAFILE_MISSING\nhelp[2]:\n"
          "  Set TASKS_DATAFILE=/path/to/datafile.py and retry\n"
          "  Or put `datafile` on your PATH")
    raise SystemExit(1)

_spec = importlib.util.spec_from_file_location("_datafile", _DF)
df = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(df)


CONTRACT = """\
# Contract for tasks.jsonl. Generated by `tasks.py init`; edit freely.
name: Task
key: id
extra: forbid

fields:
  id:          {type: str, pattern: '^[a-z][a-z0-9-]{2,47}$'}
  title:       {type: str, min_length: 1, max_length: 120}
  status:      {type: enum, values: [todo, doing, done, blocked], default: todo}
  verify:      {type: str, min_length: 1}
  verify_kind: {type: enum, values: [cmd, prose], default: cmd}
  deps:        {type: list, items: str, default: []}
  context:     {type: list, items: str, default: []}
  project:     {type: str, required: false, min_length: 1, max_length: 40}
  cwd:         {type: str, required: false}
  base:        {type: str, required: false, min_length: 1}
  owner:       {type: str, required: false}
  reason:      {type: str, required: false}
  updated:     {type: datetime}
"""


# ----------------------------------------------------------------- primitives

def _now() -> str:
    return datetime.now(UTC).isoformat()


def _age(dt: datetime) -> str:
    if dt.tzinfo is None:                      # hand-edited row: assume UTC
        dt = dt.replace(tzinfo=UTC)
    secs = (datetime.now(UTC) - dt).total_seconds()
    if secs < 3600:
        return f"{max(0, int(secs // 60))}m"
    if secs < 86400:
        return f"{int(secs // 3600)}h"
    return f"{int(secs // 86400)}d"


def _aware(dt: datetime) -> datetime:
    """Sorting mixes stored rows with hand-edited ones, and Python refuses to
    compare a naive datetime with an aware one. The view that runs on every
    session start must not be the thing that raises."""
    return dt.replace(tzinfo=UTC) if dt.tzinfo is None else dt


def _days(dt: datetime) -> float:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return (datetime.now(UTC) - dt).total_seconds() / 86400


def _slug(title: str, taken) -> str:
    """Ids are derived from the title, never invented by the caller: the id is
    then self-describing in every later output."""
    words = [w for w in re.split(r"[^a-z0-9]+", title.lower()) if w]
    s = ""
    for w in words:                            # whole words up to the budget
        if s and len(s) + 1 + len(w) > SLUG_BUDGET:
            break
        s = f"{s}-{w}" if s else w
    parts = s.split("-")
    while len(parts) > 1 and parts[-1] in SLUG_STOP:   # never end on a stopword
        parts.pop()
    s = "-".join(parts)
    if not s or not s[0].isalpha():
        s = "t-" + s if s else "task"
    s = s[:48]
    while len(s) < 3:
        s += "-t"
    if s not in taken:
        return s
    for n in range(2, 1000):
        cand = f"{s[:48 - len(str(n)) - 1]}-{n}"
        if cand not in taken:
            return cand
    raise df.AxiError(f"cannot derive a free id from {title!r}", "ID_EXHAUSTED",
                      exit_code=2)


def _open(args):
    path = getattr(args, "file", None) or STORE
    cpath = df.find_contract(path)
    if not cpath:
        raise df.AxiError(
            f"no contract found for {path}", "NO_CONTRACT",
            [f"Run `{PROG} init` to create schema-tasks.yaml beside it"],
            exit_code=1)
    model, key = df.load_contract(cpath)
    return df.Store(path, model, key)


def _need(store, rid: str):
    t = store.get(rid)
    if t is None:
        raise df.AxiError(f"task not found: {rid}", "NOT_FOUND",
                          [f"Run `{PROG} list` to see task ids"], exit_code=1)
    return t


def _save(store, task, **changes):
    d = task.model_dump(mode="json")
    d.update(changes)
    d["updated"] = _now()
    return store.put(d)


def _guard_in_flight(t, force: bool, action: str) -> None:
    """A task in `doing` belongs to its owner; the orchestrator treats it as
    read-only. Turns a silent lost update into a loud error."""
    if t.status == "doing" and not force:
        raise df.AxiError(
            f"{t.id} is in flight, owned by {t.owner or 'unknown'}",
            "TASK_IN_FLIGHT",
            [f"Run `{PROG} {action} --force` to override the owner",
             f"Run `{PROG} reset {t.id} --reason \"<why>\"` to reclaim it first"],
            exit_code=1)


# ------------------------------------------------------------------ dep graph

def _deps_met(t, tasks) -> bool:
    # A dep that no longer exists was dropped deliberately; it can never
    # complete, so treating it as unmet would block the task forever.
    return all(tasks[d].status == "done" for d in t.deps if d in tasks)


def _unmet(t, tasks) -> list[str]:
    return [d for d in t.deps if d in tasks and tasks[d].status != "done"]


def _cycle(tasks) -> list[str] | None:
    """Return one dependency cycle, or None. `dep` refuses to create one, but a
    hand-edited file or a --force can, and a cycle silently empties the ready
    set - the one failure that would quietly stall the fleet."""
    color: dict[str, int] = {}
    stack: list[str] = []

    def visit(n):
        color[n], _ = 1, stack.append(n)
        for d in tasks[n].deps:
            if d not in tasks:
                continue
            if color.get(d, 0) == 1:
                return [*stack[stack.index(d):], d]
            if color.get(d, 0) == 0 and (r := visit(d)):
                return r
        color[n] = 2
        stack.pop()
        return None

    for n in tasks:
        if color.get(n, 0) == 0 and (r := visit(n)):
            return r
    return None


def _ready(tasks) -> list:
    return sorted((t for t in tasks.values()
                   if t.status == "todo" and _deps_met(t, tasks)),
                  key=lambda t: _aware(t.updated))


def _is_stale(t) -> bool:
    """Blocked ages too. A task blocked on something only a human can decide is
    the one kind the orchestrator cannot resolve itself, so elapsed time is the
    only signal that it needs escalating rather than waiting."""
    return t.status in ("todo", "blocked") and _days(t.updated) >= STALE_DAYS


def _stale(tasks) -> list:
    return [t for t in tasks.values() if _is_stale(t)]


# --------------------------------------------------------------------- verify

def _store_dir(store) -> str:
    return os.path.dirname(os.path.abspath(store.path)) or "."


def _resolve_cwd(raw: str, store) -> str:
    """Where a task's work and its verification happen. A relative path is
    relative to the store, which is what the store-directory default already
    meant; `~` is kept in the record so it stays readable and portable."""
    p = os.path.expanduser(raw)
    return p if os.path.isabs(p) else os.path.join(_store_dir(store), p)


def _need_dir(path: str, exit_code: int):
    """A verify that runs in the wrong tree can pass by accident, so a missing
    directory is a loud error rather than a silent fall back to the store."""
    if not os.path.isdir(path):
        raise df.AxiError(f"no such directory: {df.collapse_home(path)}", "NO_SUCH_CWD",
                          [f"Run `{PROG} list --fields id,cwd` to see where tasks point"],
                          exit_code=exit_code)
    return path


def _run_verify(cmd: str, cwd: str, timeout: int):
    """Returns (ok, exit_code, output_tail). The verify string is a command the
    store's own operator authored, so it runs through the shell as written."""
    try:
        p = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True,
                           text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return False, None, f"timed out after {timeout}s"
    tail = "\n".join((p.stdout + p.stderr).splitlines()[-TAIL_LINES:])
    return p.returncode == 0, p.returncode, tail


# -------------------------------------------------------------------- commands

def cmd_init(args) -> int:
    path = args.file or STORE
    d = os.path.dirname(os.path.abspath(path))
    stem = os.path.basename(path)[:-6] if path.endswith(".jsonl") else os.path.basename(path)
    target = os.path.join(d, f"schema-{stem}.yaml")
    existing = df.find_contract(path)
    if existing:                                        # 6: idempotent
        df.emit({"contract": df.collapse_home(os.path.abspath(existing)),
                 "status": "unchanged",
                 "help": [f"Run `{PROG} add \"<title>\" --verify \"<cmd>\"` to create a task"]})
        return 0
    with open(target, "w", encoding="utf-8") as f:
        f.write(CONTRACT)
    df.emit({"contract": df.collapse_home(target), "status": "created",
             "store": path,
             "help": [f"Run `{PROG} add \"<title>\" --verify \"<cmd>\"` to create the first task"]})
    return 0


def _identity() -> dict:
    """10: name the tool before the live data, so an agent that met this output
    in a session hook knows what produced it and how to run it again."""
    return {"bin": df.collapse_home(os.path.abspath(__file__)),
            "description": DESCRIPTION,
            "version": VERSION}


def cmd_home(args) -> int:
    out = _identity()
    if not df.find_contract(args.file or STORE):
        # 5: directory-scoped and definitive. An error here would make the
        # session hook shout in every unrelated repository.
        out["tasks"] = f"no task store in {df.collapse_home(os.getcwd())}"
        out["help"] = [f"Run `{PROG} init` to create one here"]
        df.emit(out)
        return 0
    store = _open(args)
    tasks, bad = store.load()
    if not tasks:                                       # 5: definitive empty
        out["tasks"] = "0 of 0 total"
        out["store"] = store.path
        out["help"] = [f"Run `{PROG} add \"<title>\" --verify \"<cmd>\"` "
                       f"to create the first task"]
        df.emit(out)
        return 0

    by = {s: [t for t in tasks.values() if t.status == s] for s in STATUSES}
    ready, stale = _ready(tasks), _stale(tasks)
    clipped = False

    # In flight first: a cold-starting session asks "where did I leave off?"
    # before it asks "what is next?".
    if by["doing"]:
        out["doing"] = [{"id": t.id, "owner": t.owner or "-", "age": _age(t.updated)}
                        for t in sorted(by["doing"], key=lambda t: _aware(t.updated))]
    if ready:
        rows = []
        for t in ready[:HOME_LIMIT]:
            title, full = df.truncate(t.title, CELL)
            clipped = clipped or full is not None
            rows.append({"id": t.id, "title": title})
        out["ready"] = rows
    if by["blocked"]:
        # Oldest first, with age: nothing else in the store reveals that a
        # reason has been waiting for an answer since last month.
        rows = []
        for t in sorted(by["blocked"], key=lambda t: _aware(t.updated)):
            reason, full = df.truncate(t.reason or "-", CELL)
            clipped = clipped or full is not None
            rows.append({"id": t.id, "reason": reason, "age": _age(t.updated)})
        out["blocked"] = rows

    out["counts"] = [{"doing": len(by["doing"]), "ready": len(ready),
                      "todo": len(by["todo"]), "done": len(by["done"]),
                      "blocked": len(by["blocked"]), "stale": len(stale)}]

    open_n = len(by["todo"]) + len(by["doing"]) + len(by["blocked"])
    if not ready and open_n:                            # 5: name the cause
        cycle = _cycle(tasks)
        if cycle:
            out["cause"] = "dependency cycle: no task can ever become ready"
            out["cycle"] = cycle
        elif not by["todo"]:
            out["cause"] = (f"nothing queued: {len(by['doing'])} in flight, "
                            f"{len(by['blocked'])} blocked")
        else:
            out["cause"] = f"every queued task is waiting on deps ({len(by['blocked'])} blocked)"
    if bad:
        out["unreadable_lines"] = len(bad)

    help_lines = []
    if len(ready) > HOME_LIMIT:                 # 9: reveal the cap, do not encode it
        help_lines.append(f"Run `{PROG} list --status todo` to see all "
                          f"{len(ready)} ready tasks")
    if out.get("cycle"):        # a cycle stalls the whole queue: lead with it
        help_lines.append(f"Run `{PROG} dep --help`; break the cycle by dropping "
                          f"and re-adding {out['cycle'][0]} without its dep")
    if ready:
        help_lines.append(f"Run `{PROG} start {ready[0].id} --owner <minion>` "
                          f"to dispatch the next task")
    if by["doing"]:
        help_lines.append(f"Run `{PROG} show {by['doing'][0].id}` for what a minion is holding")
    if by["blocked"]:
        help_lines.append(f"Run `{PROG} list --status blocked` for what is stuck")
    if stale and len(help_lines) < 3:
        help_lines.append(f"Run `{PROG} list --stale` for {len(stale)} tasks "
                          f"untouched over {STALE_DAYS}d")
    if clipped:                                 # 3: name the escape hatch
        help_lines.append(f"Run `{PROG} show <id>` for untruncated values")
    if not help_lines:
        help_lines.append(f"Run `{PROG} add \"<title>\" --verify \"<cmd>\"` to queue more work")
    out["help"] = help_lines[:3]
    df.emit(out)
    return 0


def cmd_add(args) -> int:
    store = _open(args)
    tasks, _ = store.load()
    missing = [d for d in args.dep if d not in tasks]
    if missing:
        raise df.AxiError(f"unknown dependency: {', '.join(missing)}", "UNKNOWN_DEP",
                          [f"Run `{PROG} list` to see task ids"], exit_code=2)
    if args.cwd:
        _need_dir(_resolve_cwd(args.cwd, store), 2)
    rid = _slug(args.title, tasks)
    store.put({"id": rid, "title": args.title, "status": "todo",
               "verify": args.verify, "verify_kind": "prose" if args.prose else "cmd",
               "deps": args.dep, "context": args.context,
               "project": args.project or None, "cwd": args.cwd,
               "base": args.base or None,
               "updated": _now()})
    ready = not args.dep or all(tasks[d].status == "done" for d in args.dep)
    df.emit({"id": rid, "status": "todo", "ready": ready,
             "help": [f"Run `{PROG} start {rid} --owner <minion>` to dispatch it" if ready
                      else f"Run `{PROG} show {rid}` to see what it is waiting on"]})
    return 0


def cmd_show(args) -> int:
    store = _open(args)
    tasks, _ = store.load()
    t = tasks.get(args.id) or _need(store, args.id)
    rec = t.model_dump(mode="json")
    clipped = None
    if not args.full:
        rec["verify"], clipped = df.truncate(rec["verify"], df.DETAIL_TRUNCATE)
        if clipped:
            rec["verify_length"] = clipped
    out = {"task": rec}
    unmet = _unmet(t, tasks)
    out["ready"] = t.status == "todo" and not unmet
    if unmet:
        out["unmet_deps"] = unmet
    hint = {
        "todo": f"Run `{PROG} start {t.id} --owner <minion>` to dispatch it",
        "doing": f"Run `{PROG} done {t.id}` when the work verifies",
        "blocked": f"Run `{PROG} unblock {t.id}` once the blocker is cleared",
        "done": f"Run `{PROG}` for the next ready task",
    }[t.status]
    # 3: name the escape hatch only when there is something behind it
    out["help"] = ([f"Run `{PROG} show {t.id} --full` for the complete verify", hint]
                   if clipped else [hint])
    df.emit(out)
    return 0


def cmd_list(args) -> int:
    store = _open(args)
    if args.fields:                     # 6: a usage error must not read the log
        fields = [f.strip() for f in args.fields.split(",") if f.strip()]
        unknown = [f for f in fields if f not in store.model.model_fields]
        if unknown:
            raise df.AxiError(
                f"unknown field(s): {', '.join(unknown)}", "USAGE_ERROR",
                [f"Valid fields: {', '.join(store.model.model_fields)}"], exit_code=2)
    else:
        fields = list(LIST_FIELDS)      # 2: the smallest schema that decides

    tasks, bad = store.load()
    rows = list(tasks.values())
    total = len(rows)
    if args.status:
        rows = [t for t in rows if t.status == args.status]
    if args.project:
        rows = [t for t in rows if t.project == args.project]
    if args.stale:
        rows = [t for t in rows if _is_stale(t)]
    rows.sort(key=lambda t: (STATUSES.index(t.status), _aware(t.updated)))
    shown = rows[:args.limit]

    cells, clipped = [], False
    for t in shown:
        d = t.model_dump(mode="json")
        row = {}
        for f in fields:
            v = d.get(f)
            if not df._is_scalar(v):    # deps/context would break the TOON table
                v = json.dumps(v, ensure_ascii=False, separators=(",", ":"))
            v, full = df.truncate(v, CELL)
            clipped = clipped or full is not None
            row[f] = v
        cells.append(row)

    out = {"count": f"{len(shown)} of {total} total"}    # 4: aggregate
    if cells:
        out["tasks"] = cells
    if bad:
        out["unreadable_lines"] = len(bad)

    if not shown:
        help_lines = [f"Run `{PROG} list` without filters to see all {total}"]
    else:
        detail = "for one task with all fields"
        help_lines = [f"Run `{PROG} show <id>` {'untruncated' if clipped else detail}"]
        if len(shown) == args.limit and args.limit < len(rows):   # 9: reveal the cap
            help_lines.append(f"Run `{PROG} list --limit {len(rows)}` "
                              f"for all {len(rows)} matches")
    out["help"] = help_lines
    df.emit(out)
    return 0


def cmd_start(args) -> int:
    store = _open(args)
    tasks, _ = store.load()
    t = tasks.get(args.id) or _need(store, args.id)
    # Where the work happens can only be known at dispatch: a minion isolated in its
    # own worktree verifies there, not in the shared tree the task was written
    # against. Omitting --cwd keeps whatever the task already carries.
    if args.cwd:
        _need_dir(_resolve_cwd(args.cwd, store), 2)
    cwd = args.cwd or t.cwd
    if t.status == "doing" and t.owner == args.owner:   # 6: idempotent
        # Same minion, new directory, is a redispatch elsewhere, not a no-op. Letting
        # it pass silently would leave the task verifying in the tree it was retargeted
        # away from, which is the false green this field exists to prevent.
        if cwd != t.cwd:
            _save(store, t, cwd=cwd)
        df.emit({"id": t.id, "status": "doing", "owner": t.owner, "cwd": cwd,
                 "result": "unchanged" if cwd == t.cwd else "retargeted",
                 "help": [f"Run `{PROG} done {t.id}` when the work verifies"]})
        return 0
    _guard_in_flight(t, args.force, f"start {args.id} --owner {args.owner}")
    if t.status == "done":
        raise df.AxiError(f"{t.id} is already done", "INVALID_TRANSITION",
                          [f"Run `{PROG} show {t.id}` to see it"], exit_code=1)
    unmet = _unmet(t, tasks)
    if unmet and not args.force:
        raise df.AxiError(f"{t.id} has {len(unmet)} unmet dependency(ies)", "DEPS_UNMET",
                          [f"Run `{PROG} show {t.id}` to see them"],
                          exit_code=1, extra={"unmet_deps": unmet})
    _save(store, t, status="doing", owner=args.owner, reason=None, cwd=cwd)
    df.emit({"id": t.id, "status": "doing", "owner": args.owner, "cwd": cwd,
             "verify_kind": t.verify_kind,
             "help": [f"Run `{PROG} done {t.id}` when the work verifies",
                      f"Run `{PROG} block {t.id} --reason \"<why>\"` if it cannot proceed"]})
    return 0


def cmd_done(args) -> int:
    store = _open(args)
    t = _need(store, args.id)
    if t.status == "done":                              # 6: idempotent, no rerun
        df.emit({"id": t.id, "status": "done", "result": "unchanged",
                 "help": [f"Run `{PROG}` for the next ready task"]})
        return 0
    if t.status == "blocked":
        raise df.AxiError(f"{t.id} is blocked: {t.reason or 'no reason recorded'}",
                          "INVALID_TRANSITION",
                          [f"Run `{PROG} unblock {t.id}` first"], exit_code=1)

    if args.force:
        if not args.reason:
            raise df.AxiError("--force requires --reason", "REASON_REQUIRED",
                              [f"Run `{PROG} done {t.id} --force --reason \"<why>\"`"],
                              exit_code=2)
        _save(store, t, status="done", reason=args.reason)
        df.emit({"id": t.id, "status": "done", "verified": False,
                 "reason": args.reason,
                 "help": [f"Run `{PROG}` for the next ready task"]})
        return 0

    if t.verify_kind == "prose":
        # Prose is deliberately more work than a command: the friction is the
        # pressure toward machine-checkable verification.
        if not args.reason:
            raise df.AxiError("this task verifies by prose criterion", "REASON_REQUIRED",
                              [f"Run `{PROG} done {t.id} --reason \"<how it is satisfied>\"`"],
                              exit_code=2, extra={"criterion": df.truncate(t.verify, CELL)[0]})
        _save(store, t, status="done", reason=args.reason)
        df.emit({"id": t.id, "status": "done", "verified": "asserted",
                 "help": [f"Run `{PROG}` for the next ready task"]})
        return 0

    cwd = _need_dir(_resolve_cwd(t.cwd, store), 1) if t.cwd else _store_dir(store)
    ok, code, tail = _run_verify(t.verify, cwd, args.timeout)
    if not ok:
        shown, full = df.truncate(tail, df.DETAIL_TRUNCATE)
        extra = {"command": df.truncate(t.verify, CELL)[0], "exit_code": code,
                 "output": shown}
        if full:                        # 3: never omit silently, show the size
            extra["output_length"] = full
        raise df.AxiError(f"verify failed for {t.id}", "VERIFY_FAILED",
                          [f"Run `{PROG} block {t.id} --reason \"<why>\"` if it cannot proceed",
                           f"Run `{PROG} done {t.id} --force --reason \"<why>\"` to override"],
                          exit_code=1, extra=extra)
    _save(store, t, status="done", reason=None)
    df.emit({"id": t.id, "status": "done", "verified": True,
             "help": [f"Run `{PROG}` for the next ready task"]})
    return 0


def cmd_block(args) -> int:
    store = _open(args)
    t = _need(store, args.id)
    if t.status == "blocked" and t.reason == args.reason:
        df.emit({"id": t.id, "status": "blocked", "result": "unchanged",
                 "help": [f"Run `{PROG} unblock {t.id}` once the blocker is cleared"]})
        return 0
    if t.status == "done":
        raise df.AxiError(f"{t.id} is already done", "INVALID_TRANSITION",
                          [f"Run `{PROG} show {t.id}` to see it"], exit_code=1)
    _save(store, t, status="blocked", reason=args.reason)
    df.emit({"id": t.id, "status": "blocked", "reason": args.reason,
             "help": [f"Run `{PROG} add \"<title>\" --verify \"<cmd>\"` then "
                      f"`{PROG} dep {t.id} --on <new-id>` to queue the unblocker"]})
    return 0


def _to_todo(store, t, *, clear_owner: bool, reason: str | None = None):
    return _save(store, t, status="todo", reason=reason,
                 owner=None if clear_owner else t.owner)


def cmd_unblock(args) -> int:
    store = _open(args)
    tasks, _ = store.load()
    t = tasks.get(args.id) or _need(store, args.id)
    if t.status == "todo":
        df.emit({"id": t.id, "status": "todo", "result": "unchanged",
                 "help": [f"Run `{PROG} start {t.id} --owner <minion>` to dispatch it"]})
        return 0
    if t.status != "blocked":
        raise df.AxiError(f"{t.id} is {t.status}, not blocked", "INVALID_TRANSITION",
                          [f"Run `{PROG} show {t.id}` to see it"], exit_code=1)
    _to_todo(store, t, clear_owner=False)
    unmet = _unmet(t, tasks)
    df.emit({"id": t.id, "status": "todo", "ready": not unmet,
             "help": [f"Run `{PROG} start {t.id} --owner <minion>` to dispatch it" if not unmet
                      else f"Run `{PROG} show {t.id}` to see what it is waiting on"]})
    return 0


def cmd_reset(args) -> int:
    """Orphan reaper: the orchestrator died mid-flight and the fleet is gone."""
    store = _open(args)
    t = _need(store, args.id)
    if t.status == "todo":
        df.emit({"id": t.id, "status": "todo", "result": "unchanged",
                 "help": [f"Run `{PROG} start {t.id} --owner <minion>` to dispatch it"]})
        return 0
    if t.status == "done":
        raise df.AxiError(f"{t.id} is done; reset would discard a verified result",
                          "INVALID_TRANSITION",
                          [f"Run `{PROG} show {t.id}` to see it"], exit_code=1)
    prior = t.owner
    # Keep the reason on the record: it is why this is back in the queue, and
    # `start` clears it on redispatch, so it never outlives its usefulness.
    _to_todo(store, t, clear_owner=True, reason=args.reason)
    df.emit({"id": t.id, "status": "todo", "reclaimed_from": prior or "-",
             "reason": args.reason,
             "help": [f"Run `{PROG} start {t.id} --owner <minion>` to redispatch it"]})
    return 0


def cmd_dep(args) -> int:
    store = _open(args)
    tasks, _ = store.load()
    t = tasks.get(args.id) or _need(store, args.id)
    if args.on not in tasks:
        raise df.AxiError(f"unknown dependency: {args.on}", "UNKNOWN_DEP",
                          [f"Run `{PROG} list` to see task ids"], exit_code=2)
    if args.on == args.id:
        raise df.AxiError(f"{args.id} cannot depend on itself", "DEP_CYCLE", exit_code=2)
    if args.on in t.deps:
        df.emit({"id": t.id, "deps": t.deps, "result": "unchanged",
                 "help": [f"Run `{PROG} show {t.id}` to see it"]})
        return 0
    _guard_in_flight(t, args.force, f"dep {args.id} --on {args.on}")

    probe = dict(tasks)
    deps = [*t.deps, args.on]
    probe[t.id] = t.model_copy(update={"deps": deps})
    if cycle := _cycle(probe):
        raise df.AxiError(f"{args.on} -> {args.id} would create a dependency cycle",
                          "DEP_CYCLE", [f"Run `{PROG} show {args.on}` to see its deps"],
                          exit_code=2, extra={"cycle": cycle})

    _save(store, t, deps=deps)
    df.emit({"id": t.id, "deps": deps, "ready": not _unmet(probe[t.id], tasks),
             "help": [f"Run `{PROG} show {t.id}` to see what it is waiting on"]})
    return 0


def cmd_drop(args) -> int:
    store = _open(args)
    t = store.get(args.id)
    if t is None:                                       # 6: idempotent no-op
        df.emit({"id": args.id, "result": "absent",
                 "help": [f"Run `{PROG} list` to see task ids"]})
        return 0
    _guard_in_flight(t, args.force, f"drop {args.id}")
    # Write the reason first: delete only appends a tombstone, so this is what
    # keeps "why" recoverable from the raw log after the record is gone.
    _save(store, t, reason=args.reason)
    store.delete(args.id)
    df.emit({"id": args.id, "result": "dropped", "reason": args.reason,
             "help": [f"Run `{PROG}` for the current queue"]})
    return 0


# ------------------------------------------------ session integrations (§7)

def _is_managed(hook: dict) -> bool:
    return AMBIENT_FLAG in (hook.get("command") or "")


def _hook_update(settings: dict, command: str) -> tuple[dict, str]:
    """Claude Code and Codex share the hooks.SessionStart group shape."""
    updated = json.loads(json.dumps(settings))
    if not isinstance(updated.get("hooks"), dict):
        updated["hooks"] = {}
    hooks = updated["hooks"]
    if not isinstance(hooks.get("SessionStart"), list):
        hooks["SessionStart"] = []

    for group in hooks["SessionStart"]:
        for hook in group.get("hooks") or []:
            if not _is_managed(hook):
                continue
            if (hook.get("command") == command and hook.get("type") == "command"
                    and hook.get("timeout") == HOOK_TIMEOUT):
                return settings, "unchanged (no-op)"
            hook.update(type="command", command=command, timeout=HOOK_TIMEOUT)
            return updated, "repaired"      # 7: path repair after a reinstall

    hooks["SessionStart"].append({"matcher": "", "hooks": [
        {"type": "command", "command": command, "timeout": HOOK_TIMEOUT}]})
    return updated, "installed"


def _hook_removal(settings: dict) -> tuple[dict, bool]:
    updated = json.loads(json.dumps(settings))
    hooks = updated.get("hooks")
    if not isinstance(hooks, dict) or not isinstance(hooks.get("SessionStart"), list):
        return settings, False
    changed, remaining = False, []
    for group in hooks["SessionStart"]:
        inner = [h for h in (group.get("hooks") or []) if not _is_managed(h)]
        if len(inner) != len(group.get("hooks") or []):
            changed = True
            if not inner:
                continue
            group = {**group, "hooks": inner}
        remaining.append(group)
    if not changed:
        return settings, False
    if remaining:
        hooks["SessionStart"] = remaining
    else:
        hooks.pop("SessionStart", None)
    if not hooks:
        updated.pop("hooks", None)
    return updated, True


def _opencode_plugin(argv: list[str]) -> str:
    """OpenCode has no SessionStart hook, so the home view is injected as
    ambient system context instead, cached once per session."""
    return f"""// {OPENCODE_PREFIX} {TOOL_NAME}
// Generated by tasks.py. Safe to edit only if you remove the marker above.
import {{ spawn }} from "node:child_process";

const argv = {json.dumps(argv)};
const header = {json.dumps(f"## AXI ambient context: {TOOL_NAME}")};
const timeoutMs = {HOOK_TIMEOUT * 1000};

function runHomeView(cwd) {{
  return new Promise((resolve) => {{
    const child = spawn(argv[0], argv.slice(1), {{
      cwd: cwd || process.cwd(), env: process.env, shell: false,
      stdio: ["ignore", "pipe", "pipe"],
    }});
    let stdout = "", settled = false;
    const done = (v) => {{ if (!settled) {{ settled = true; clearTimeout(timer); resolve(v); }} }};
    const timer = setTimeout(() => {{ child.kill("SIGTERM"); done(""); }}, timeoutMs);
    child.stdout?.setEncoding("utf-8");
    child.stdout?.on("data", (c) => {{ stdout += c; }});
    child.on("error", () => done(""));
    child.on("close", (code) => done(code === 0 ? stdout.trim() : ""));
  }});
}}

export const agentTasksAmbientContext = async ({{ directory }}) => {{
  const cache = new Map();
  return {{
    "experimental.chat.system.transform": async (input, output) => {{
      const id = input.sessionID ?? "__global__";
      let view = cache.get(id);
      if (view === undefined) {{ view = await runHomeView(directory); cache.set(id, view); }}
      if (view.length === 0) return;
      output.system.push(header + "\n" + view);
    }},
  }};
}};
"""


def _opencode_path(t: dict) -> str:
    return os.path.join(t["opencode"], f"axi-{TOOL_NAME}.js")


def cmd_ambient(args) -> int:
    """The session-hook entry point. Silent where there is no store, and never
    non-zero: a task manager must not be able to break a session start."""
    if not df.find_contract(args.file or STORE):
        return 0
    try:
        cmd_home(args)
    except (df.AxiError, df.ContractError, OSError) as e:
        df.emit({"error": str(e), "code": "AMBIENT_DEGRADED",
                 "help": [f"Run `{PROG}` here to see the full error"]})
    return 0


def cmd_setup(args) -> int:
    uv = shutil.which("uv")
    if not uv:
        raise df.AxiError("uv not found on PATH", "SETUP_ERROR",
                          [f"Install uv, then re-run `{PROG} setup`"], exit_code=1)
    me = os.path.abspath(__file__)
    argv = [*df._hook_argv(uv, me), AMBIENT_FLAG]
    command = " ".join(argv)
    t = df._hook_targets(args.scope)
    apps = ["claude", "codex", "opencode"] if args.app == "all" else [args.app]
    rows, extra = [], {}

    def status_of(app: str) -> str:
        if app == "opencode":
            head = (df._read_text(_opencode_path(t)) or "").split("\n", 1)[0]
            return "installed" if OPENCODE_PREFIX in head else "absent"
        groups = (df._read_json(t[app]).get("hooks") or {}).get("SessionStart") or []
        found = any(_is_managed(h) for g in groups for h in (g.get("hooks") or []))
        return "installed" if found else "absent"

    if args.status:
        for app in apps:
            path = _opencode_path(t) if app == "opencode" else t[app]
            rows.append({"app": app, "status": status_of(app),
                         "path": df.collapse_home(path)})
        stale = df.codex_config_update(df._read_text(t["codex_config"]) or "")[1]
        df.emit({"scope": args.scope, "targets": rows,
                 "codex_hooks_feature": "disabled" if stale else "enabled",
                 "help": [f"Run `{PROG} setup` to install",
                          f"Run `{PROG} setup --uninstall` to remove"]})
        return 0

    for app in apps:
        if app == "opencode":
            path = _opencode_path(t)
            if args.uninstall:
                status = "already absent (no-op)"
                if status_of("opencode") != "absent":
                    os.unlink(path)
                    status = "removed"
            else:
                want, have = _opencode_plugin(argv), df._read_text(path)
                if have == want:                        # 7: idempotent
                    status = "unchanged (no-op)"
                else:
                    df._write(path, want)
                    status = "repaired" if have else "installed"
            rows.append({"app": app, "status": status, "path": df.collapse_home(path)})
            continue

        data = df._read_json(t[app])
        if args.uninstall:
            updated, ch = _hook_removal(data)
            status = "removed" if ch else "already absent (no-op)"
        else:
            updated, status = _hook_update(data, command)
        if not status.endswith("(no-op)"):
            df._write(t[app], json.dumps(updated, indent=2) + "\n")
        rows.append({"app": app, "status": status, "path": df.collapse_home(t[app])})

        if app == "codex" and not args.uninstall:
            # Repo-level Codex hooks still need the user-level feature flag.
            cfg = t["codex_config"]
            new, ch = df.codex_config_update(df._read_text(cfg) or "")
            if ch:
                df._write(cfg, new)
            extra["codex_hooks_feature"] = (
                f"enabled in {df.collapse_home(cfg)}" if ch
                else f"already enabled in {df.collapse_home(cfg)}")

    out = {"scope": args.scope, "command": command, "targets": rows}
    out.update(extra)
    out["help"] = ([f"Run `{PROG} setup --status` to verify"] if args.uninstall else
                   [f"Run `{PROG} setup --status` to verify",
                    f"Run `{PROG} setup --uninstall` to remove",
                    f"Run `{PROG} skill --install` for the on-demand skill instead"])
    df.emit(out)
    return 0


# --------------------------------------------------- installable skill (§7)

def render_skill() -> str:
    """Generated from the parser, so the skill cannot drift from the CLI. Static
    by construction: it names no store, no task, and no machine-specific path."""
    _parser, reg = build_parser()
    body = [
        "---",
        f"name: {SKILL_NAME}",
        "description: >-",
    ]
    row = ""
    for w in SKILL_TRIGGER.split():
        if len(row) + len(w) + 1 > 76:
            body.append(f"  {row}")
            row = w
        else:
            row = f"{row} {w}".strip()
    body += [f"  {row}", "---", "", f"# {SKILL_NAME}", "", DESCRIPTION + ".", "",
             "## Ownership", "",
             "One orchestrator creates tasks and dispatches them. Each worker updates",
             "only the task it owns. A task in `doing` belongs to its owner, and the",
             "orchestrator treats it as read-only; ownership transfers on `start` and",
             "returns on any terminal transition. Workers never create tasks: a worker",
             "that finds new work runs `block`, and the orchestrator queues the",
             "unblocker and wires it with `dep`.", "",
             "## Verification", "",
             "Every task carries a `--verify` command that `done` runs; a non-zero exit",
             "refuses the transition. `--prose` marks a criterion asserted instead, and",
             "`done` then requires `--reason`. `--force --reason` overrides either and",
             "records why, so a forced completion stays distinguishable from a verified",
             "one.", "",
             "## Commands", "",
             f"Run `{PROG} <command> --help` for the full reference on any of these.", ""]
    for name, sp in reg.items():
        usage = " ".join(sp.format_usage().split()).replace("usage: ", "").replace(" [-h]", "")
        body += [f"### {name}", "", sp.description or "", "", "```sh", usage, "```", ""]
    body += ["## Output", "",
             "TOON on stdout, including errors; nothing is written to stderr.",
             "Exit 0 is success including idempotent no-ops, 1 means the request",
             "could not be satisfied, 2 is a usage or contract error.", ""]
    return "\n".join(body)


def _skill_path(scope: str, app: str) -> str:
    root = os.path.expanduser("~") if scope == "user" else os.getcwd()
    return os.path.join(root, *SKILL_APPS[app], SKILL_NAME, "SKILL.md")


def _skill_place(path: str, want: str, args) -> str:
    if args.uninstall:
        have = df._read_text(path)
        if have is None:
            return "already absent (no-op)"
        if f"name: {SKILL_NAME}" not in have:
            raise df.AxiError(
                f"{df.collapse_home(path)} was not generated by this tool",
                "SKILL_FOREIGN", ["Remove it by hand if you are sure"], exit_code=1)
        os.unlink(path)
        with contextlib.suppress(OSError):
            os.rmdir(os.path.dirname(path))
        return "removed"
    have = df._read_text(path)
    if have == want:
        return "unchanged (no-op)"
    df._write(path, want)
    return "regenerated" if have else "installed"


def cmd_skill(args) -> int:
    if args.out and args.install:
        raise df.AxiError("--out and --install choose different destinations",
                          "USAGE_ERROR",
                          [f"Run `{PROG} skill --install` to install it for an agent",
                           f"Run `{PROG} skill --out <path>` to write a copy"],
                          exit_code=2)
    want = render_skill()

    if args.install or args.uninstall:
        apps = list(SKILL_APPS) if args.app == "all" else [args.app]
        rows = [{"app": a, "status": _skill_place(_skill_path(args.scope, a), want, args),
                 "path": df.collapse_home(os.path.dirname(_skill_path(args.scope, a)))}
                for a in apps]
        df.emit({"scope": args.scope, "targets": rows,
                 "help": ([f"Run `{PROG} skill --install` to reinstall"] if args.uninstall
                          else [f"Restart your agent session to pick up {SKILL_NAME}",
                                f"Run `{PROG} skill --uninstall` to remove it"])})
        return 0

    out = args.out or SKILL_PATH
    have = df._read_text(out)

    if args.check:                      # 7: CI gate against a stale skill
        if have is None:
            raise df.AxiError(f"{out} does not exist", "SKILL_STALE",
                              [f"Run `{PROG} skill` to generate it"], exit_code=1)
        if have != want:
            raise df.AxiError(f"{out} is out of date", "SKILL_STALE",
                              [f"Run `{PROG} skill` to regenerate it"], exit_code=1)
        df.emit({"skill": f"{out} is up to date"})
        return 0

    if have == want:
        df.emit({"skill": f"{df.collapse_home(out)} unchanged (no-op)"})
        return 0
    df._write(out, want)
    df.emit({"skill": f"{'regenerated' if have else 'generated'} {df.collapse_home(out)}",
             "lines": len(want.splitlines()),
             "help": [f"Run `{PROG} skill --install` to install it for your agents",
                      f"Run `{PROG} skill --check` in CI to fail on a stale skill"]})
    return 0


# ----------------------------------------------------------- pi package (§7)

def _pi_extension(argv: list[str]) -> str:
    """pi has no command-hook mechanism; extensions are TypeScript modules.
    `session_start` captures the view once, `before_agent_start` appends it."""
    candidates = [[BIN_NAME, AMBIENT_FLAG], argv]
    return f"""// Generated by tasks.py. Regenerate with `tasks.py pi-package`.
import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";
import {{ spawn }} from "node:child_process";

// Tried in order. The bare name works when {BIN_NAME} is on PATH, which is what
// makes this package usable on someone else's machine; the second entry is the
// absolute path baked in when the package was generated.
const CANDIDATES: string[][] = {json.dumps(candidates)};
const TIMEOUT_MS = {HOOK_TIMEOUT * 1000};
const HEADER = {json.dumps(f"## AXI ambient context: {TOOL_NAME}")};

function tryOne(argv: string[], cwd: string): Promise<string | null> {{
  return new Promise((resolve) => {{
    const child = spawn(argv[0], argv.slice(1), {{
      cwd, env: process.env, shell: false, stdio: ["ignore", "pipe", "pipe"],
    }});
    let out = "";
    let settled = false;
    const done = (value: string | null) => {{
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    }};
    // Timed out: give up rather than fall through to the next candidate.
    const timer = setTimeout(() => {{ child.kill("SIGTERM"); done(""); }}, TIMEOUT_MS);
    child.stdout?.setEncoding("utf-8");
    child.stdout?.on("data", (chunk) => {{ out += chunk; }});
    // null means "this candidate is unusable, try the next one".
    child.on("error", () => done(null));
    child.on("close", (code) => done(code === 0 ? out.trim() : null));
  }});
}}

async function homeView(cwd: string): Promise<string> {{
  for (const argv of CANDIDATES) {{
    const result = await tryOne(argv, cwd);
    // Ambient context is best-effort: a failure must not corrupt the prompt.
    if (result !== null) return result;
  }}
  return "";
}}

export default function (pi: ExtensionAPI) {{
  let ambient = "";

  pi.on("session_start", async (_event, ctx) => {{
    ambient = await homeView(ctx.cwd);
  }});

  pi.on("before_agent_start", async (event) => {{
    // Empty in a directory with no task store, and it stays out of the prompt.
    if (!ambient) return;
    return {{ systemPrompt: `${{event.systemPrompt}}\\n\\n${{HEADER}}\\n${{ambient}}` }};
  }});
}}
"""


def _pi_manifest() -> str:
    return json.dumps({
        "name": PI_PACKAGE_DIR,
        "version": VERSION,
        "type": "module",              # the extension is ESM TypeScript
        "description": DESCRIPTION,
        "keywords": ["pi-package", "tasks", "agents", "axi"],
        "pi": {"extensions": ["./extensions"], "skills": ["./skills"]},
        "peerDependencies": {"@earendil-works/pi-coding-agent": "*"},
        "private": True,
    }, indent=2) + "\n"


def _pi_readme(argv: list[str]) -> str:
    return f"""# {PI_PACKAGE_DIR}

A [pi package](https://pi.dev) for {TOOL_NAME}: {DESCRIPTION.lower()}.

Generated by `tasks.py pi-package`. Do not edit by hand - regenerate instead.
`tasks.py pi-package --check` catches drift, but only on the machine that
generated the package: the absolute fallback path below is baked in at
generation time, so the check fails anywhere else. In CI, check the skill
instead - it carries no machine-specific paths.

## Install

```sh
pi install /path/to/{PI_PACKAGE_DIR}
```

Add `-l` to install into this project's `.pi/settings.json` instead of your
account.

## What it provides

- **skills/{SKILL_NAME}/SKILL.md** - loaded on demand when a task involves
  queueing, dispatching, or verifying work for a fleet of agents.
- **extensions/ambient-context.ts** - captures the queue at `session_start` and
  appends it to the system prompt, so a session opens already knowing what is in
  flight, what is ready, and what is stuck.

The extension shells out to `{BIN_NAME}` if it is on `PATH`, otherwise to the
absolute path baked in when this package was generated:

```
{" ".join(argv)}
```

For the package to work on another machine, install `{BIN_NAME}` on `PATH`
there. Otherwise regenerate the package on that machine.

In a directory with no task store the command prints nothing, and the extension
leaves the system prompt untouched.
"""


def _pi_files(argv: list[str]) -> dict[str, str]:
    return {
        "package.json": _pi_manifest(),
        "README.md": _pi_readme(argv),
        os.path.join("extensions", "ambient-context.ts"): _pi_extension(argv),
        os.path.join("skills", SKILL_NAME, "SKILL.md"): render_skill(),
    }


def cmd_pi_package(args) -> int:
    uv = shutil.which("uv")
    if not uv:
        raise df.AxiError("uv not found on PATH", "SETUP_ERROR",
                          [f"Install uv, then re-run `{PROG} pi-package`"], exit_code=1)
    root = args.out or PI_PACKAGE_DIR
    files = _pi_files([*df._hook_argv(uv, os.path.abspath(__file__)), AMBIENT_FLAG])
    stale = [rel for rel, want in files.items()
             if df._read_text(os.path.join(root, rel)) != want]

    if args.check:
        if stale:
            raise df.AxiError(f"{df.collapse_home(root)} is out of date", "PACKAGE_STALE",
                              [f"Run `{PROG} pi-package` to regenerate it"],
                              exit_code=1, extra={"stale": sorted(stale)})
        df.emit({"package": f"{df.collapse_home(root)} is up to date"})
        return 0

    if not stale:
        df.emit({"package": f"{df.collapse_home(root)} unchanged (no-op)"})
        return 0
    for rel, want in files.items():
        df._write(os.path.join(root, rel), want)
    df.emit({"package": df.collapse_home(root), "files": sorted(files),
             "help": [f"Run `pi install {os.path.abspath(root)}` to install it",
                      f"Run `{PROG} pi-package --check` to catch drift on this "
                      f"machine (it bakes in an absolute path, so it fails elsewhere)"]})
    return 0


# -------------------------------------------------------------------- parsing

def build_parser():
    p = df.AxiParser(prog=PROG, description=DESCRIPTION)
    p.add_argument("--file", "-f", help=f"path to the task store (default: {STORE})")
    p.add_argument("--version", "-v", "-V", action="store_true", help="print version")
    p.add_argument(AMBIENT_FLAG, action="store_true",
                   help="session-hook mode: print nothing where there is no store")
    subs = p.add_subparsers(dest="cmd", metavar="<command>")
    reg: dict = {}

    def add(name, help_text, epilog, fn):
        sp = subs.add_parser(name, help=help_text, description=help_text,
                             epilog=epilog,
                             formatter_class=df.argparse.RawDescriptionHelpFormatter)
        sp.set_defaults(func=fn)
        reg[name] = sp
        return sp

    add("init", "create the contract for the task store",
        f"Example:\n  {PROG} init", cmd_init)

    sp = add("add", "create a task (orchestrator only)",
             f"Examples:\n  {PROG} add \"Parse CLI flags\" --verify \"pytest -k flags\"\n"
             f"  {PROG} add \"Ship it\" --verify \"a human confirms it\" "
             f"--prose --dep parse-cli-flags",
             cmd_add)
    sp.add_argument("title")
    sp.add_argument("--verify", required=True,
                    help="command that exits 0 when done, or a prose criterion with --prose")
    sp.add_argument("--prose", action="store_true",
                    help="--verify is a criterion to assert, not a command to run")
    sp.add_argument("--dep", action="append", default=[], metavar="ID",
                    help="task that must be done first (repeatable)")
    sp.add_argument("--project", metavar="HANDLE",
                    help="the project this task belongs to; a stable grouping handle "
                         "that survives --cwd being retargeted at dispatch")
    sp.add_argument("--cwd", metavar="DIR",
                    help="where the work happens and where --verify runs "
                         "(default: the store's directory)")
    sp.add_argument("--base", metavar="REF",
                    help="ref this task's work starts from; the dispatcher branches "
                         "the minion's worktree here (default: the project's checkout)")
    sp.add_argument("--context", action="append", default=[], metavar="PATH",
                    help="pointer a cold-starting agent should read (repeatable)")

    sp = add("show", "one task with all fields",
             f"Example:\n  {PROG} show parse-cli-flags", cmd_show)
    sp.add_argument("id")
    sp.add_argument("--full", action="store_true", help="do not truncate verify")

    sp = add("list", "tasks as a table",
             f"Examples:\n  {PROG} list --status blocked\n  {PROG} list --stale", cmd_list)
    sp.add_argument("--status", choices=STATUSES)
    sp.add_argument("--project", metavar="HANDLE", help="only this project's tasks")
    sp.add_argument("--stale", action="store_true",
                    help=f"todo or blocked, untouched for over {STALE_DAYS} days")
    sp.add_argument("--fields", metavar="A,B,C",
                    help=f"comma-separated fields (default: {','.join(LIST_FIELDS)})")
    sp.add_argument("--limit", type=int, default=df.DEFAULT_LIMIT)

    sp = add("start", "dispatch a task to a minion (orchestrator only)",
             f"Examples:\n  {PROG} start parse-cli-flags --owner minion-3\n"
             f"  {PROG} start parse-cli-flags --owner minion-3 --cwd ~/worktrees/parse-cli-flags",
             cmd_start)
    sp.add_argument("id")
    sp.add_argument("--owner", required=True, help="the minion taking the task")
    sp.add_argument("--cwd", metavar="DIR",
                    help="retarget where the work happens and where --verify runs, "
                         "for a minion isolated in its own worktree")
    sp.add_argument("--force", action="store_true",
                    help="take a task another owner holds, or with unmet deps")

    sp = add("done", "finish a task; runs its verify command (owner only)",
             f"Examples:\n  {PROG} done parse-cli-flags\n"
             f"  {PROG} done ship-it --reason \"demo confirmed on staging\"", cmd_done)
    sp.add_argument("id")
    sp.add_argument("--reason", help="required for prose verification or --force")
    sp.add_argument("--force", action="store_true", help="skip verification; records the reason")
    sp.add_argument("--timeout", type=int, default=VERIFY_TIMEOUT,
                    help=f"seconds before verify is killed (default: {VERIFY_TIMEOUT})")

    sp = add("block", "mark a task stuck (owner only)",
             f"Example:\n  {PROG} block ship-it --reason \"needs the flag parser first\"",
             cmd_block)
    sp.add_argument("id")
    sp.add_argument("--reason", required=True)

    sp = add("unblock", "return a blocked task to the queue",
             f"Example:\n  {PROG} unblock ship-it", cmd_unblock)
    sp.add_argument("id")

    sp = add("reset", "reclaim an orphaned in-flight task",
             f"Example:\n  {PROG} reset parse-cli-flags --reason \"orchestrator restarted\"",
             cmd_reset)
    sp.add_argument("id")
    sp.add_argument("--reason", required=True)

    sp = add("dep", "make one task wait on another",
             f"Example:\n  {PROG} dep ship-it --on parse-cli-flags", cmd_dep)
    sp.add_argument("id")
    sp.add_argument("--on", required=True, metavar="ID")
    sp.add_argument("--force", action="store_true", help="edit a task that is in flight")

    sp = add("setup", "install the session-start integration (§7)",
             f"Examples:\n  {PROG} setup\n  {PROG} setup --status\n"
             f"  {PROG} setup --scope project --app claude", cmd_setup)
    sp.add_argument("--scope", choices=["user", "project"], default="user",
                    help="install for every session, or only this directory")
    sp.add_argument("--app", choices=["all", "claude", "codex", "opencode"],
                    default="all")
    sp.add_argument("--status", action="store_true", help="report without changing anything")
    sp.add_argument("--uninstall", action="store_true", help="remove the integration")

    sp = add("skill", "generate the on-demand agent skill (§7)",
             f"Examples:\n  {PROG} skill --install\n  {PROG} skill --check\n"
             f"  {PROG} skill --out SKILL.md", cmd_skill)
    sp.add_argument("--out", help=f"output path (default: {SKILL_PATH})")
    sp.add_argument("--install", action="store_true", help="write it where agents look")
    sp.add_argument("--uninstall", action="store_true", help="remove an installed copy")
    sp.add_argument("--scope", choices=["user", "project"], default="user")
    sp.add_argument("--app", choices=["all", "claude", "pi"], default="all")
    sp.add_argument("--check", action="store_true",
                    help="exit 1 if the committed skill is stale")

    sp = add("pi-package", "generate the pi package (§7)",
             f"Examples:\n  {PROG} pi-package\n  {PROG} pi-package --check",
             cmd_pi_package)
    sp.add_argument("--out", help=f"package directory (default: {PI_PACKAGE_DIR})")
    sp.add_argument("--check", action="store_true",
                    help="exit 1 if the committed package is stale")

    sp = add("drop", "remove a task from the queue",
             f"Example:\n  {PROG} drop stale-idea --reason \"superseded\"", cmd_drop)
    sp.add_argument("id")
    sp.add_argument("--reason", required=True)
    sp.add_argument("--force", action="store_true", help="drop a task that is in flight")

    return p, reg


def main(argv=None) -> int:
    global PROG
    if argv is None:
        PROG = os.path.basename(sys.argv[0]) or PROG
        argv = sys.argv[1:]
    parser, reg = build_parser()
    try:
        args = parser.parse_args(list(argv))
    except df._Usage as e:
        # 6: the agent's next move after an unknown flag is `--help`; inline it.
        # Globals sit on the top-level parser and must precede the subcommand,
        # so they are named separately rather than listed as the subcommand's.
        sub = next((a for a in argv if a in reg), None)
        if sub:
            flags = ", ".join(df._flags_of(reg[sub]))
            hint = [f"valid flags for `{sub}`: {flags} "
                    f"(globals, before the subcommand: --file, --version)",
                    f"Run `{PROG} {sub} --help` for the full reference"]
        else:
            hint = [f"commands: {', '.join(sorted(reg))}",
                    f"valid flags for `{PROG}`: {', '.join(df._flags_of(parser))}",
                    f"Run `{PROG} --help` for the full reference"]
        return df.fail(df.AxiError(str(e.message), "USAGE_ERROR", hint, exit_code=2))

    if getattr(args, "version", False):
        print(VERSION)
        return 0
    try:
        if getattr(args, "cmd", None):
            return args.func(args)
        return cmd_ambient(args) if args.ambient else cmd_home(args)
    except df.AxiError as e:
        return df.fail(e)
    except df.ContractError as e:
        return df.fail(df.AxiError(str(e), "CONTRACT_ERROR",
                                   [f"Run `{PROG} init` to regenerate the contract"],
                                   exit_code=2))
    except OSError as e:
        return df.fail(df.AxiError(f"{e.strerror or e}: {e.filename or ''}".strip(),
                                   "IO_ERROR", exit_code=1))


if __name__ == "__main__":
    raise SystemExit(main())
