// Generated by tasks.py. Regenerate with `tasks.py pi-package`.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "node:child_process";

// Tried in order. The bare name works when tasks is on PATH, which is what
// makes this package usable on someone else's machine; the second entry is the
// absolute path baked in when the package was generated.
const CANDIDATES: string[][] = [["tasks", "--ambient"], ["tasks", "--ambient"]];
const TIMEOUT_MS = 10000;
const HEADER = "## AXI ambient context: agent-tasks";

function tryOne(argv: string[], cwd: string): Promise<string | null> {
  return new Promise((resolve) => {
    const child = spawn(argv[0], argv.slice(1), {
      cwd, env: process.env, shell: false, stdio: ["ignore", "pipe", "pipe"],
    });
    let out = "";
    let settled = false;
    const done = (value: string | null) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };
    // Timed out: give up rather than fall through to the next candidate.
    const timer = setTimeout(() => { child.kill("SIGTERM"); done(""); }, TIMEOUT_MS);
    child.stdout?.setEncoding("utf-8");
    child.stdout?.on("data", (chunk) => { out += chunk; });
    // null means "this candidate is unusable, try the next one".
    child.on("error", () => done(null));
    child.on("close", (code) => done(code === 0 ? out.trim() : null));
  });
}

async function homeView(cwd: string): Promise<string> {
  for (const argv of CANDIDATES) {
    const result = await tryOne(argv, cwd);
    // Ambient context is best-effort: a failure must not corrupt the prompt.
    if (result !== null) return result;
  }
  return "";
}

export default function (pi: ExtensionAPI) {
  let ambient = "";

  pi.on("session_start", async (_event, ctx) => {
    ambient = await homeView(ctx.cwd);
  });

  pi.on("before_agent_start", async (event) => {
    // Empty in a directory with no task store, and it stays out of the prompt.
    if (!ambient) return;
    return { systemPrompt: `${event.systemPrompt}\n\n${HEADER}\n${ambient}` };
  });
}
